apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        traffic.sidecar.istio.io/excludeOutboundPorts: "9092,27017,3306,6379"
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: ghcr.io/alpha3002025/{{ .Values.appName }}-svc:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Values.appName }}
        ports:
        - containerPort: {{ .Values.portNumber }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Djava.net.preferIPv4Stack=true"
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.profile }}
        - name: SERVER_PORT
          value: "{{ .Values.portNumber }}"
        {{- with .Values.envValues }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.debugValues}}
        {{- with .Values.debugValues}}
        {{- toYaml . | nindent 8 }}
        {{- end}}
        {{- end}}
        {{- if .Values.configSecretItems}}
        envFrom:
          {{- range .Values.configSecretItems }}
          - configMapRef:
              name: {{ . | trimSuffix "-nosecret" }}-config
          {{- if not (hasSuffix "-nosecret" .)}}
          - secretRef:
              name: {{ . }}-secret
          {{- end}}
          {{- end}}
        {{- end}}
        resources: 
          requests:
            memory: {{ .Values.resources.memory.requests }}
            cpu: {{ .Values.resources.cpu.requests }}
          limits:
            memory: {{ .Values.resources.memory.limits }}
            cpu: {{ .Values.resources.cpu.limits }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        {{- with .Values.probeValues.readiness }}
        readinessProbe:
          httpGet:
            path: {{ .httpGetPath }}
            port: {{ $.Values.portNumber }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- with .Values.probeValues.liveness }}
        livenessProbe:
          httpGet:
            path: {{ .httpGetPath }}
            port: {{ $.Values.portNumber }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          failureThreshold: {{ .failureThreshold }}
        {{- end}}
        {{- with .Values.probeValues.startup}}
        startupProbe:
          httpGet:
            path: {{ .httpGetPath }}
            port: {{ $.Values.portNumber }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          failureThreshold: {{ .failureThreshold }}
        {{- end}}
        {{- if .Values.persistence }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: {{ .Values.appName }}-storage
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
        {{- end }}
      {{- if .Values.persistence }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: {{ .Values.appName }}-storage
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}-claim
      {{- end }}
      {{- end }}
status: {}