profile: local
namespace: dailyfeed
imageTag: 0.0.2
appName: dailyfeed-backend
replicas: 3
envValues: [] ## 각 서비스마다 필요에 따라 다르게 지정
configSecretItems: [] ## 각 서비스마다 필요에 따라 다르게 지정
resources:
  memory:
    requests: "400Mi"
    limits: "800Mi"
  cpu:
    requests: "30m"
    limits: "100m"
probeValues:
  readiness:
    httpGetPath: /healthcheck/ready
    httpGetPort: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGetPath: /healthcheck/live
    httpGetPort: 8080
    initialDelaySeconds: 5
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 3
  startup:
    httpGetPath: /healthcheck/startup
    httpGetPort: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 80
persistence:
  enabled: false
  storageClass: local-path
  storageRequest: "1Gi"
  accessModes:
  - ReadWriteOnce
  mountPath: /image
